import mage.abilities.Ability;
import mage.abilities.ActivatedAbility;
import mage.cards.Card;
import mage.cards.CardImpl;
import mage.cards.CardSetInfo;
import mage.cards.ExpansionSet;

import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * Writes a set-wide action vocabulary for ActionEncoder (the MZ_ACTION_VOCAB file the generalist
 * XMage build and MageZero's policy width both read). Build and run it with tools/vocab/build_vocab.sh.
 *
 * Moved into draft-zero from the archived MageZero-Experiments workspace (fdn-generalist,
 * experiments/action_vocab/java/tools), where it generated assets/vocab/FDN_SPG.tsv for exp #1.
 *
 *   java -cp "xmage/lib/*:tools-classes" VocabDump mage.sets.Foundations 1024 > FDN.tsv
 *   java ... VocabDump mage.sets.Foundations,mage.sets.SpecialGuests 1024 extra_cards.txt > FDN.tsv
 *
 * Several comma-separated sets may be given. The first is included in full; later sets (e.g.
 * Special Guests, which spans many releases) are limited to the card names listed one per line in
 * the optional third argument, when given.
 *
 * Action keys are exactly what ActionEncoder.getActionIndex sees: ability.toString() of every
 * ActivatedAbility on every card in the set (spells: "Cast X", lands: "Play X", mana and other
 * activated abilities by rules text). Target keys are card names; MCTSNode looks targets up by
 * game.getEntityName(), which is the object name. Tokens and anything else not listed fall into
 * the hashed tail at runtime.
 */
public class VocabDump {
    public static void main(String[] args) throws Exception {
        String[] setClasses = args[0].split(",");
        int dim = Integer.parseInt(args[1]);
        Set<String> extraCards = args.length > 2
                ? new HashSet<>(java.nio.file.Files.readAllLines(java.nio.file.Paths.get(args[2]), StandardCharsets.UTF_8))
                : null;
        List<ExpansionSet> sets = new ArrayList<>();
        for (String c : setClasses) {
            sets.add((ExpansionSet) Class.forName(c.trim()).getMethod("getInstance").invoke(null));
        }
        ExpansionSet set = sets.get(0);

        // reserved entries keep the upstream indices so "Pass"/mana/players mean the same thing
        LinkedHashMap<String, Integer> actions = new LinkedHashMap<>();
        for (String s : new String[]{"Pass", "{T}: Add {B}.", "{T}: Add {G}.", "{T}: Add {R}.",
                "{T}: Add {U}.", "{T}: Add {W}.", "{T}: Add {C}."}) {
            actions.put(s, actions.size());
        }
        LinkedHashMap<String, Integer> targets = new LinkedHashMap<>();
        for (String s : new String[]{"Stop Choosing", "PlayerA", "PlayerB"}) {
            targets.put(s, targets.size());
        }

        TreeSet<String> actionKeys = new TreeSet<>();
        TreeSet<String> targetKeys = new TreeSet<>();
        int cards = 0, failed = 0;
        for (ExpansionSet s : sets)
        for (ExpansionSet.SetCardInfo info : s.getSetCardInfo()) {
            if (s != set && extraCards != null && !extraCards.contains(info.getName())) continue;
            Card card;
            try {
                card = CardImpl.createCard(info.getCardClass(),
                        new CardSetInfo(info.getName(), s.getCode(), info.getCardNumber(), info.getRarity()));
            } catch (Throwable t) {
                failed++;
                System.err.println("could not create " + info.getName() + ": " + t);
                continue;
            }
            if (card == null) { failed++; continue; }
            cards++;
            targetKeys.add(card.getName());
            for (Ability a : card.getAbilities()) {
                if (a instanceof ActivatedAbility) {
                    actionKeys.add(a.toString());
                }
            }
        }
        for (String k : actionKeys) actions.putIfAbsent(k, actions.size());
        for (String k : targetKeys) targets.putIfAbsent(k, targets.size());

        if (actions.size() >= dim - 32 || targets.size() >= dim - 32) {
            throw new IllegalStateException("dim " + dim + " too small: " + actions.size() + " actions, "
                    + targets.size() + " targets (need >= 32 hashed tail slots)");
        }

        PrintWriter out = new PrintWriter(new java.io.OutputStreamWriter(System.out, StandardCharsets.UTF_8));
        StringBuilder codes = new StringBuilder(set.getCode());
        for (ExpansionSet s : sets.subList(1, sets.size())) codes.append("+").append(s.getCode());
        out.println("# action vocabulary for " + codes + " (" + set.getName() + "), generated by VocabDump");
        out.println("# " + cards + " card printings, " + actions.size() + " actions, " + targets.size()
                + " targets; indices >= those counts are the hashed tail");
        out.println("dim\t" + dim);
        for (Map.Entry<String, Integer> e : actions.entrySet()) {
            out.println("A\t" + e.getValue() + "\t" + e.getKey().replace("\n", "\\n"));
        }
        for (Map.Entry<String, Integer> e : targets.entrySet()) {
            out.println("T\t" + e.getValue() + "\t" + e.getKey().replace("\n", "\\n"));
        }
        out.flush();
        System.err.println(set.getCode() + ": " + cards + " cards (" + failed + " failed), "
                + actions.size() + " actions, " + targets.size() + " targets, dim " + dim);
    }
}
